indexing-settings:
  sites:
    - url: https://nikoartgallery.com/
      name: Галлерея Нико
    - url: https://nopaper.ru/
      name: NoPaper


spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 4568

server:
  port: 8081

