indexing-settings:
  sites:
    - url: http://e.kipu-rc.ru
      name: Skillbox


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 4568

server:
  port: 8081

