indexing-settings:
  sites:
    - url: https://playback.ru/
      name: PlayBack.Ru

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 4568

server:
  port: 8081

